---
# dataverse/tasks/dataverse-apache.yml

- name: install Apache for RedHat/CentOS
  yum: name="{{item}}" state=latest
  with_items:
    - httpd
    - mod_ssl
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install http redirect template
  template: src=http.redirect.conf.j2 dest=/etc/httpd/conf.d/http.redirect.conf
        owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install proxy error boilerplate
  copy: src=503.html dest=/etc/httpd/conf.d owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: enable and start httpd on RedHat/CentOS 7
  service: name=httpd enabled=yes state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
