---
# dataverse/tasks/main.yml

- include: dataverse-prereqs.yml
  tags: prereqs

- include: dataverse-apache.yml
  tags: apache

- include: dataverse-shibboleth.yml
  when: dataverse.shibboleth.enabled == True
  tags: shibboleth

- include: dataverse-postgres.yml
  tags: postgres

# ----- works up to here
# must manually kill the glassfi+ process before rerunning
#  when restarting must use sudo unless you su as glassfish 
- include: dataverse-glassfish.yml
  tags: glassfish

# manually change the version of solr, 7.9 rather than 4.6.0
# Must manually kill/stop BOTH solr and glassfish before rerunning
- include: dataverse-solr.yml
  tags: solr

- include: dataverse-install.yml
  tags: dataverse

- include: dataverse-postinstall.yml
  tags: postinstall
